### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by JackBekket** [ihtfw/rss-telegram-bot#1]
Привет Вадим! 

К сожалению не смог найти твоих контактов, поэтому пишу сюда

Я заметил твою работу над matrix/riot под андроид, и хотел бы узнать по поводу возможной коллаборации

В данный момент я пилю новый проект с гиперлокальными чатами на платформе matrix

Я успешно портировал libp2p под андроид и хочу сделать форк Riot, внедрив туда этот функционал. 
К сожалению у меня нет большого опыта разработки на java, поэтому я решил посмотреть кто уже занимался подобными сборками, и хотел бы узнать можешь ли ты или твоя команда мне с этим помочь. 

Можем обсудить детали и условия вознаграждения, если это предложение будет тебе интересно.

Мои контакты для связи - telegram @sbekket

**Comment by ihtfw** [comment]
Привет.

Тут есть небольшая проблема, что я сам в андроид не силен(вообще я C# WPF разработчик)

Делаю очень маленькие фичи и исправления для знакомых, которые готовы были заплатить за это т.к. используют riot в работе и кое-что их не устраивало, но что-то серьезно менять в архитектуре это уже выше моих сил.

Спасибо за предложение в любом случае, но вряд ли я смогу тут чем-то особо помочь.
